<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML
><HEAD
><TITLE
>明示的サブトランザクション</TITLE
><META
NAME="GENERATOR"
CONTENT="Modular DocBook HTML Stylesheet Version "><LINK
REV="MADE"
HREF="mailto:pgsql-docs@postgresql.org"><LINK
REL="HOME"
TITLE="PostgreSQL 9.1.4文書"
HREF="index.html"><LINK
REL="UP"
TITLE="PL/Python - Python手続き言語"
HREF="plpython.html"><LINK
REL="PREVIOUS"
TITLE="データベースアクセス"
HREF="plpython-database.html"><LINK
REL="NEXT"
TITLE="ユーティリティ関数"
HREF="plpython-util.html"><LINK
REL="STYLESHEET"
TYPE="text/css"
HREF="stylesheet.css"><META
HTTP-EQUIV="Content-Type"
CONTENT="text/html; charset=euc-jp"><META
NAME="creation"
CONTENT="2012-06-16T03:12:10"></HEAD
><BODY
CLASS="SECT1"
><script type="text/javascript">
var mod_layout = 'test';
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-50659-6");
pageTracker._trackPageview();
</script>
<style>
body{margin:0;}
#lay_body{margin:8px;}
#lay_header{margin:0 0 4px 0;border:0;padding:0;}
#lay_header .b1{border-bottom:#cef solid 1px;}
#lay_header .b2{border-bottom:#8df solid 1px;}
#lay_header .b3{border-bottom:#4bf solid 1px;padding:5px 5px 3px 5px;background:#0af;text-align:center;color:#fff;}
#lay_header a{text-decoration:none;color:#fff;font-weight:bold;}
#lay_header a:hover{text-decoration:underline;}
</style>
<div id="lay_header"><div class="b1"><div class="b2"><div class="b3">
<a href="http://lets.postgresql.jp/" target="_blank">PostgreSQLポータルサイト ＜Let's Postgres＞ http://lets.postgresql.jp/</a><br>
入門から運用、チューニングノウハウ、新機能の解説など、幅広い内容の技術解説記事をお読みいただけます。
</div></div></div></div>
<div id="lay_body">
<DIV
CLASS="NAVHEADER"
><TABLE
SUMMARY="Header navigation table"
WIDTH="100%"
BORDER="0"
CELLPADDING="0"
CELLSPACING="0"
><TR
><TH
COLSPAN="5"
ALIGN="center"
VALIGN="bottom"
><A
HREF="index.html"
>PostgreSQL 9.1.4文書</A
></TH
></TR
><TR
><TD
WIDTH="10%"
ALIGN="left"
VALIGN="top"
><A
TITLE="データベースアクセス"
HREF="plpython-database.html"
ACCESSKEY="P"
>&#21069;&#12398;&#12506;&#12540;&#12472;</A
></TD
><TD
WIDTH="10%"
ALIGN="left"
VALIGN="top"
><A
TITLE="PL/Python - Python手続き言語"
HREF="plpython.html"
>&#24059;&#25147;&#12375;</A
></TD
><TD
WIDTH="60%"
ALIGN="center"
VALIGN="bottom"
>&#31532; 42&#31456;PL/Python - Python手続き言語</TD
><TD
WIDTH="10%"
ALIGN="right"
VALIGN="top"
><A
TITLE="PL/Python - Python手続き言語"
HREF="plpython.html"
>&#26089;&#36865;&#12426;</A
></TD
><TD
WIDTH="10%"
ALIGN="right"
VALIGN="top"
><A
TITLE="ユーティリティ関数"
HREF="plpython-util.html"
ACCESSKEY="N"
>&#27425;&#12398;&#12506;&#12540;&#12472;</A
></TD
></TR
></TABLE
><HR
ALIGN="LEFT"
WIDTH="100%"></DIV
><DIV
CLASS="SECT1"
><H1
CLASS="SECT1"
><A
NAME="PLPYTHON-SUBTRANSACTION"
>42.8. 明示的サブトランザクション</A
></H1
><P
><A
HREF="plpython-database.html#PLPYTHON-TRAPPING"
>&#38917;42.7.2</A
>で説明したデータベースアクセスによって引き起こるエラーからの復旧は、操作の中の１つが失敗する前に、一部の操作が成功し、エラーからの復旧の後一貫性のないデータが残ってしまうという望ましくない状態を導く可能性があります。
PL/Pythonは明示的サブトランザクションにより、この問題の解法を提供します。
  </P
><DIV
CLASS="SECT2"
><H2
CLASS="SECT2"
><A
NAME="AEN56961"
>42.8.1. サブトランザクションのコンテキスト管理</A
></H2
><P
>2つの口座の間の振替えを実装する関数を考えてみます。
</P><PRE
CLASS="PROGRAMLISTING"
>CREATE FUNCTION transfer_funds() RETURNS void AS $$
try:
    plpy.execute("UPDATE accounts SET balance = balance - 100 WHERE account_name = 'joe'")
    plpy.execute("UPDATE accounts SET balance = balance + 100 WHERE account_name = 'mary'")
except plpy.SPIError, e:
    result = "error transferring funds: %s" % e.args
else:
    result = "funds transferred correctly"
plan = plpy.prepare("INSERT INTO operations (result) VALUES ($1)", ["text"])
plpy.execute(plan, [result])
$$ LANGUAGE plpythonu;</PRE
><P>
2番目の<TT
CLASS="LITERAL"
>UPDATE</TT
>文が例外を発生させる結果となった場合、この関数はエラーを記録しますが、それにもかかわらず最初の<TT
CLASS="LITERAL"
>UPDATE</TT
>はコミットされます。
言い換えると、資金はジョーの口座から引き落とされますが、メアリーの口座には移転しません。
   </P
><P
>こうした問題を防ぐために、<TT
CLASS="LITERAL"
>plpy.execute</TT
>呼び出しを明示的なサブトランザクションで囲むことができます。
<TT
CLASS="LITERAL"
>plpy</TT
>モジュールは、<TT
CLASS="LITERAL"
>plpy.subtransaction()</TT
>関数で作成される明示的なサブトランザクションを管理するための補助オブジェクトを提供します。
この関数によって作成されるオブジェクトは<A
HREF="http://docs.python.org/library/stdtypes.html#context-manager-types"
TARGET="_top"
>コンテキストマネージャインタフェース</A
>を実装します
明示的なサブトランザクションを使用して、上の関数を以下のように書き換えることができます。
</P><PRE
CLASS="PROGRAMLISTING"
>CREATE FUNCTION transfer_funds2() RETURNS void AS $$
try:
    with plpy.subtransaction():
        plpy.execute("UPDATE accounts SET balance = balance - 100 WHERE account_name = 'joe'")
        plpy.execute("UPDATE accounts SET balance = balance + 100 WHERE account_name = 'mary'")
except plpy.SPIError, e:
    result = "error transferring funds: %s" % e.args
else:
    result = "funds transferred correctly"
plan = plpy.prepare("INSERT INTO operations (result) VALUES ($1)", ["text"])
plpy.execute(plan, [result])
$$ LANGUAGE plpythonu;</PRE
><P>
<TT
CLASS="LITERAL"
>try/catch</TT
>の使用がまだ必要なことに注意してください。
さもないと例外がPythonスタックの最上位まで伝播され、関数全体が<SPAN
CLASS="PRODUCTNAME"
>PostgreSQL</SPAN
>エラーにより中断され、この結果、<TT
CLASS="LITERAL"
>operations</TT
>テーブルには挿入されるはずの行が存在しないことになります。
サブトランザクションのコンテキストマネージャはエラーを捕捉しません。
これはそのスコープの内側で実行されるデータベース操作すべてが、原子的にコミットされるかロールバックされるかだけを保証します。
サブトランザクションブロックのロールバックは、データベースアクセスを元にしたエラーによって引き起こる例外だけではなく、何らかの種類の例外終了でも起こります。
明示的なサブトランザクションブロックの内側で発生した通常のPython例外も同様にサブトランザクションをロールバックさせます。
   </P
></DIV
><DIV
CLASS="SECT2"
><H2
CLASS="SECT2"
><A
NAME="AEN56976"
>42.8.2. Pythonの旧式バージョン</A
></H2
><P
>デフォルトでは、<TT
CLASS="LITERAL"
>with</TT
>キーワードを使用したコンテキストマネージャ構文はPython 2.6で利用可能です。
これより古いバージョンのPythonでPL/Pythonを使用する場合でも、透過性がありませんが、明示的なサブトランザクションを使用することができます。
サブトランザクションマネージャの<TT
CLASS="LITERAL"
>__enter__</TT
>および<TT
CLASS="LITERAL"
>__exit__</TT
>関数を、<TT
CLASS="LITERAL"
>enter</TT
>および<TT
CLASS="LITERAL"
>exit</TT
>という便利な別名を使用して、呼び出すことができます。
資金の振替えを行う関数の例は以下のように記述できます。
</P><PRE
CLASS="PROGRAMLISTING"
>CREATE FUNCTION transfer_funds_old() RETURNS void AS $$
try:
    subxact = plpy.subtransaction()
    subxact.enter()
    try:
        plpy.execute("UPDATE accounts SET balance = balance - 100 WHERE account_name = 'joe'")
        plpy.execute("UPDATE accounts SET balance = balance + 100 WHERE account_name = 'mary'")
    except:
        import sys
        subxact.exit(*sys.exc_info())
        raise
    else:
        subxact.exit(None, None, None)
except plpy.SPIError, e:
    result = "error transferring funds: %s" % e.args
else:
    result = "funds transferred correctly"

plan = plpy.prepare("INSERT INTO operations (result) VALUES ($1)", ["text"])
plpy.execute(plan, [result])
$$ LANGUAGE plpythonu;</PRE
><P>
   </P
><DIV
CLASS="NOTE"
><BLOCKQUOTE
CLASS="NOTE"
><P
><B
>&#27880;&#24847;: </B
>コンテキストマネージャはPython 2.5で実装されましたが、このバージョンで<TT
CLASS="LITERAL"
>with</TT
>構文を使用するためには<A
HREF="http://docs.python.org/release/2.5/ref/future.html"
TARGET="_top"
>future文</A
>を使用する必要があります。
しかし実装上の問題のためPL/Python関数ではfuture文を使用することができません。
    </P
></BLOCKQUOTE
></DIV
></DIV
></DIV
><DIV
CLASS="NAVFOOTER"
><HR
ALIGN="LEFT"
WIDTH="100%"><TABLE
SUMMARY="Footer navigation table"
WIDTH="100%"
BORDER="0"
CELLPADDING="0"
CELLSPACING="0"
><TR
><TD
WIDTH="33%"
ALIGN="left"
VALIGN="top"
><A
HREF="plpython-database.html"
ACCESSKEY="P"
>&#21069;&#12398;&#12506;&#12540;&#12472;</A
></TD
><TD
WIDTH="34%"
ALIGN="center"
VALIGN="top"
><A
HREF="index.html"
ACCESSKEY="H"
>&#12507;&#12540;&#12512;</A
></TD
><TD
WIDTH="33%"
ALIGN="right"
VALIGN="top"
><A
HREF="plpython-util.html"
ACCESSKEY="N"
>&#27425;&#12398;&#12506;&#12540;&#12472;</A
></TD
></TR
><TR
><TD
WIDTH="33%"
ALIGN="left"
VALIGN="top"
>データベースアクセス</TD
><TD
WIDTH="34%"
ALIGN="center"
VALIGN="top"
><A
HREF="plpython.html"
ACCESSKEY="U"
>&#19978;&#12395;&#25147;&#12427;</A
></TD
><TD
WIDTH="33%"
ALIGN="right"
VALIGN="top"
>ユーティリティ関数</TD
></TR
></TABLE
></DIV
></BODY
></HTML
></div>
